language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
# creat config file
  - python creat_config_file.py
# unit test
  - pytest
# linting test
  - flake8
