"""empty message

Revision ID: 123ab592edc9
Revises: d5c689b9a6c8
Create Date: 2019-12-26 12:19:16.660361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '123ab592edc9'
down_revision = 'd5c689b9a6c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_equipment_type_id'), 'equipment', ['type_id'], unique=False)
    op.create_index(op.f('ix_equipment_user_id'), 'equipment', ['user_id'], unique=False)
    op.drop_constraint(None, 'equipment', type_='foreignkey')
    op.create_foreign_key(None, 'equipment', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'equipment', 'equipment_types', ['type_id'], ['id'], ondelete='CASCADE')
    op.drop_column('equipment', 'type')
    op.create_index(op.f('ix_images_story_id'), 'images', ['story_id'], unique=False)
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.create_foreign_key(None, 'images', 'stories', ['story_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_stats_equipment_id'), 'stats', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_stats_story_id'), 'stats', ['story_id'], unique=False)
    op.drop_constraint(None, 'stats', type_='foreignkey')
    op.drop_constraint(None, 'stats', type_='foreignkey')
    op.create_foreign_key(None, 'stats', 'equipment', ['equipment_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'stats', 'stories', ['story_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_stories_stats_id'), 'stories', ['stats_id'], unique=False)
    op.drop_constraint(None, 'stories', type_='foreignkey')
    op.create_foreign_key(None, 'stories', 'stats', ['stats_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stories', type_='foreignkey')
    op.create_foreign_key(None, 'stories', 'stats', ['stats_id'], ['id'])
    op.drop_index(op.f('ix_stories_stats_id'), table_name='stories')
    op.drop_constraint(None, 'stats', type_='foreignkey')
    op.drop_constraint(None, 'stats', type_='foreignkey')
    op.create_foreign_key(None, 'stats', 'equipment', ['equipment_id'], ['id'])
    op.create_foreign_key(None, 'stats', 'stories', ['story_id'], ['id'])
    op.drop_index(op.f('ix_stats_story_id'), table_name='stats')
    op.drop_index(op.f('ix_stats_equipment_id'), table_name='stats')
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.create_foreign_key(None, 'images', 'stories', ['story_id'], ['id'])
    op.drop_index(op.f('ix_images_story_id'), table_name='images')
    op.add_column('equipment', sa.Column('type', sa.SMALLINT(), nullable=False))
    op.drop_constraint(None, 'equipment', type_='foreignkey')
    op.drop_constraint(None, 'equipment', type_='foreignkey')
    op.create_foreign_key(None, 'equipment', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_equipment_user_id'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_type_id'), table_name='equipment')
    # ### end Alembic commands ###
