"""empty message

Revision ID: 230e1501ad80
Revises: 6ff7ae33e479
Create Date: 2019-12-25 18:01:26.430985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '230e1501ad80'
down_revision = '6ff7ae33e479'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('EquipmentTypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_name')
    )
    op.add_column('equipment', sa.Column('type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'equipment', 'EquipmentTypes', ['type_id'], ['id'])
    op.drop_column('equipment', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('type', sa.SMALLINT(), nullable=False))
    op.drop_constraint(None, 'equipment', type_='foreignkey')
    op.drop_column('equipment', 'type_id')
    op.drop_table('EquipmentTypes')
    # ### end Alembic commands ###
