"""empty message

Revision ID: d5c689b9a6c8
Revises: 230e1501ad80
Create Date: 2019-12-25 18:06:36.401788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5c689b9a6c8'
down_revision = '230e1501ad80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_name')
    )
    op.drop_table('EquipmentTypes')
    op.create_foreign_key(None, 'equipment', 'equipment_types', ['type_id'], ['id'])
    op.drop_column('equipment', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('type', sa.SMALLINT(), nullable=False))
    op.drop_constraint(None, 'equipment', type_='foreignkey')
    op.create_table('EquipmentTypes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('type_name', sa.VARCHAR(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_name')
    )
    op.drop_table('equipment_types')
    # ### end Alembic commands ###
