"""empty message

Revision ID: f50eb87a881b
Revises: 
Create Date: 2019-12-30 19:48:02.904872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f50eb87a881b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('avatar', sa.String(length=128), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['equipment_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipment_type_id'), ['type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipment_user_id'), ['user_id'], unique=False)

    op.create_table('equipment_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_name')
    )
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('src', sa.Text(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_images_story_id'), ['story_id'], unique=False)

    op.create_table('stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('distance', sa.BigInteger(), nullable=True),
    sa.Column('time', sa.BigInteger(), nullable=True),
    sa.Column('total_time', sa.BigInteger(), nullable=True),
    sa.Column('max_speed', sa.BigInteger(), nullable=True),
    sa.Column('steps', sa.BigInteger(), nullable=True),
    sa.Column('avg_cadence', sa.SmallInteger(), nullable=True),
    sa.Column('max_cadence', sa.SmallInteger(), nullable=True),
    sa.Column('avg_heart_rate', sa.SmallInteger(), nullable=True),
    sa.Column('max_heart_rate', sa.SmallInteger(), nullable=True),
    sa.Column('max_temperature', sa.Float(), nullable=True),
    sa.Column('min_temperature', sa.Float(), nullable=True),
    sa.Column('start_altitude', sa.SmallInteger(), nullable=True),
    sa.Column('total_up_altitude', sa.SmallInteger(), nullable=True),
    sa.Column('total_down_altitude', sa.SmallInteger(), nullable=True),
    sa.Column('min_altitude', sa.SmallInteger(), nullable=True),
    sa.Column('max_altitude', sa.SmallInteger(), nullable=True),
    sa.Column('story_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stats_equipment_id'), ['equipment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stats_story_id'), ['story_id'], unique=False)

    op.create_table('stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('stats_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stats_id'], ['stats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stories_stats_id'), ['stats_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('second_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('avatar', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stories_stats_id'))

    op.drop_table('stories')
    with op.batch_alter_table('stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stats_story_id'))
        batch_op.drop_index(batch_op.f('ix_stats_equipment_id'))

    op.drop_table('stats')
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_images_story_id'))

    op.drop_table('images')
    op.drop_table('equipment_types')
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipment_user_id'))
        batch_op.drop_index(batch_op.f('ix_equipment_type_id'))

    op.drop_table('equipment')
    # ### end Alembic commands ###
