"""Image src mb None

Revision ID: f596463062c1
Revises: f50eb87a881b
Create Date: 2020-01-04 15:37:58.940724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f596463062c1'
down_revision = 'f50eb87a881b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.alter_column('src',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.alter_column('src',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
